### ISSUE TITLE
Update/revisit codecov integration/config

### ISSUE THREAD

**Issue by blueyed** [jazzband/help#135]
In/for https://github.com/jazzband/roadies/issues/8 apparently a yaml for the organization was created: https://codecov.io/account/gh/jazzband/yaml

I think we should use the new integration via https://github.com/apps/codecov/installations/new/permissions?target_id=15129049 instead, and remove the project config, as it seems to affect all projects, and overrides the default config.

But it might also make sense to set a default config here, given that most projects do not like codecov comments for example.

The following might be good, but includes comments:
```yaml
coverage:
  status:
    project: yes
    patch: yes
    changes: yes

comment:
  layout: "header, diff, flags"
  behavior: default
  require_changes: no
```

Ref: https://docs.codecov.io/docs/codecov-yaml
Ref: https://docs.codecov.io/docs/pull-request-comments
